# Uncomment the next line to define a global platform for your project

platform :ios, ‘8.0’

target 'XYPhotoBrowserDemo' do

  pod 'FLAnimatedImage'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'UUKeyboardInputView'
  
end
